"""
--
- 7/21/25 12:29 -- they seem to move together with all weights at 1. Need to bound them inside a cube and play with neighborhood sizes as some of
them seem to stop -- not sure why that is happening.
- 7/21/25 -- runs with 5 agents and a moving target but the agents scatter.
- works as a 2D grid
- 7/3/25 23:42 the open3D visualizer opens and runs while the environment is running.
"""

import argparse
from importlib.metadata import distributions

from datetime import datetime
from pathlib import Path

import numpy as np


from tqdm import tqdm  # Progress bar
import gymnasium as gym
import yaml
from loguru import logger

import pyarrow.parquet as pq
import pyarrow as pa
import shutil

from collab_env.gnn.gnn_3D.simulator_agents_abstract import SimulatorAgents
from collab_env.sim.boids.boid_agents import BoidAgents
import collab_env.sim.gymnasium_env as gymnasium_env  # noqa: F401
from collab_env.data.file_utils import get_project_root, expand_path
from collab_env.sim.boids.sim_utils import (
    function_filter,
    plot_trajectories,
    add_obs_to_df,
)


def setup_logging(config: dict, run_folder: Path) -> None:
    """
    Sets up the loguru logging for the simulator
    Args:
        config(dict): the configuration dictionary for the simulator which include logging setup information
        run_folder(Path): the output folder for the data generated by the simulator, which is where the logfile will go.
    """
    if not config["logging"]["logging"]:
        logger.disable("")
    else:
        # -- 080325 11:19AM
        # Remove the existing handlers and add a new one attached to the
        # log file in the run folder and with the prefix specified in the config
        # file.
        logger.remove()
        if len(config["logging"]["log_functions"]) > 0:
            logger.add(
                expand_path(f"{config['logging']['logfile_prefix']}.log", run_folder),
                level=config["logging"]["log_level"],
                filter=function_filter(
                    function_list=config["logging"]["log_functions"]
                ),
            )
        else:
            logger.add(
                expand_path(f"{config['logging']['logfile_prefix']}.log", run_folder),
                level=config["logging"]["log_level"],
            )


def write_package_list(run_folder: Path) -> None:
    """
    Writes the list of python packages to the run_folder to ensure reproducibility.
    Args:
        run_folder(Path): the output folder for the data generated by the simulator
    """

    package_list_file_path = expand_path("package_list.txt", run_folder)
    with open(package_list_file_path, "w") as f:
        pairs = sorted(
            (
                (dist.metadata.get("Name") or dist.name).lower(),  # type: ignore[attr-defined]
                f"{dist.metadata.get('Name') or dist.name}=={dist.version}",  # type: ignore[attr-defined]
            )
            for dist in distributions()
        )
        result = ""
        for _, line in pairs:
            result += line + "\n"
        f.write(result)


def setup_seed_list(config: dict) -> list[int]:
    """
    Args:
        config(dict): the configuration dictionary for the simulator
    Returns:
        A list of integers to serve as the random seeds for each episode.
    Raises:
        ValueError: if the number of seeds in the configuration seed list is less than the number of episodes.
    """
    #
    # There should be one seed for each episode
    #
    seed_list = config["simulator"]["seed"]
    """
    -- 122325 
    if we don't have enough seeds, bail out and give the user a list of seeds to add
    to the config.yaml file. 
    """
    if len(seed_list) < config["simulator"]["num_episodes"]:
        rng = np.random.default_rng(seed=0)
        unique_ints = rng.choice(
            np.arange(1, 1000000),
            size=config["simulator"]["num_episodes"],
            replace=False,
        )
        raise ValueError(
            f"Number of episodes ({config['simulator']['num_episodes']}) greater than number of seeds ({len(seed_list)}). Aborting. Here is a list of random seeds for each episode. Put them in the config file and rerun.\n{unique_ints.tolist()}"
        )

    return seed_list


def create_environment(
    config: dict, run_folder: Path, env_id: str = "gymnasium_env/BoidsWorldSimple-v0"
) -> gym.Env:
    """
    Args:
        config(dict): the configuration dictionary for the simulator
        run_folder(Path): the output folder for the data generated by the simulator
        env_id(str): the ID of the gymnasium environment, which determines which environment
            gymnasium will load.
    Returns:
        A gymnasium environment initialized as specified in the config dictionary.
    """
    if config["visuals"]["show_visualizer"]:
        render_mode = "human"
    else:
        render_mode = "rgb_array"  # I don't think this actually matters because we ignore this but it saves a warning.

    """ 
    -- 080825 7:15PM
    If no fixed target positions were specified, we should pass None to the environment
    """
    fixed_target_position = config["environment"]["target_position"]
    if len(fixed_target_position) == 0:
        fixed_target_position = None

    # Find the path for the video in the run folder.
    video_file_path = expand_path(
        f"video.{config['visuals']['video_file_extension']}", run_folder
    )
    config["visuals"]["video_file_path"] = video_file_path
    config["visuals"]["saved_image_path"] = run_folder

    #
    # Create environment
    #
    if env_id in config["simulator"]:
        env_id = config["simulator"]["env_id"]

    env = gym.make(
        id=env_id,
        render_mode=render_mode,
        run_trajectories=config["simulator"]["run_trajectories"]
        if "run_trajectories" in config["simulator"]
        else None,
        num_agents=config["simulator"]["num_agents"],
        num_targets=config["simulator"]["num_targets"],
        num_ground_targets=config["simulator"]["num_ground_targets"],
        walking=config["simulator"]["walking"],
        show_box=config["simulator"]["show_box"],
        store_video=config["visuals"]["store_video"],
        show_visualizer=config["visuals"]["show_visualizer"],
        vis_width=config["visuals"]["width"],
        vis_height=config["visuals"]["height"],
        video_file_path=config["visuals"]["video_file_path"],
        video_codec=config["visuals"]["video_codec"],
        video_fps=config["visuals"]["video_fps"],
        agent_shape=config["visuals"]["agent_shape"],
        agent_color=config["visuals"]["agent_color"],
        agent_scale=config["visuals"]["agent_scale"],
        target_scale=config["visuals"]["target_scale"],
        agent_mean_init_velocity=config["agent"]["mean_init_velocity"],
        agent_variance_init_velocity=config["agent"]["variance_init_velocity"],
        agent_init_range_low=config["agent"]["init_range_low"],
        agent_init_range_high=config["agent"]["init_range_high"],
        agent_height_range_low=config["agent"]["height_range_low"],
        agent_height_range_high=config["agent"]["height_range_high"],
        agent_height_init_min=config["agent"]["height_init_min"],
        agent_height_init_max=config["agent"]["height_init_max"],
        target_init_range_low=config["environment"]["init_range_low"],
        target_init_range_high=config["environment"]["init_range_high"],
        target_height_init_max=config["environment"]["height_init_max"],
        target_mesh_file=config["meshes"]["sub_mesh_target"]
        if config["simulator"]["submesh_target"]
        else None,
        target_mesh_init_color=config["visuals"]["target_mesh_init_color"],
        target_mesh_color=config["visuals"]["target_mesh_color"],
        box_size=config["environment"]["box_size"],
        scene_scale=config["environment"]["scene_scale"],
        scene_filename=config["meshes"]["mesh_scene"],
        scene_position=config["environment"]["scene_position"],
        scene_angle=np.pi * np.array(config["meshes"]["scene_angle"]) / 180.0,
        target_creation_time=config["simulator"]["target_creation_time"],
        target_positions=fixed_target_position,
        color_tracks_by_time=config["tracks"]["color_by_time"],
        number_track_color_groups=config["tracks"]["number_of_color_groups"],
        track_color_rate=config["tracks"]["track_color_rate"],
        saved_image_path=config["visuals"]["saved_image_path"],
    )

    return env


def run_simulator(
    config: dict,
    env: gym.Env,
    agents: SimulatorAgents,
    run_folder: Path,
    save_results: bool = True,
) -> None:
    """
    Args:
        config: the configuration dictionary for the simulator
        env: the gymnasium environment that executes and displays the simulation (might
            be better to make this more general enventually if we want to move away from
            using gymnasium all the time.
        agents: the simulator agents that operate in the environment
        run_folder: the output folder for the data generated by the esimulator
        save_results: whether to save the results of the simulation
    """
    #
    # Set up the random seeds for each episode. ** This will abort if there aren't enough seeds in the config file. **
    #
    seed_list = setup_seed_list(config)

    setup_logging(config, run_folder)

    # -- 080225 9:54AM
    # Copy the config file into the run folder to record configuration for the run.
    # There may be a better way to do this to make sure we get all parameters stored
    # in case there are still hardcoded values in the code -- which should be removed
    # at some point.

    # -- 080225
    # Find the path for the video in the run folder.
    video_file_path = expand_path(
        f"video.{config['visuals']['video_file_extension']}", run_folder
    )
    logger.debug(f"video path {video_file_path}")

    variant_index_list, variant_type_list = agents.get_variant_types()

    #
    # Run the episodes
    #
    for episode in tqdm(range(config["simulator"]["num_episodes"]), leave=True):
        # Start a new episode
        logger.debug(f"run_simulator(): starting episode {episode}")

        # Reset the agents
        agents.reset()

        # Reset the environment
        obs, info = env.reset(
            seed=seed_list[episode], options=agents.get_reset_options()
        )

        # Add the initial positions to the dataframe
        df = add_obs_to_df(
            None,
            obs,
            time_step=0,
            variant_index_list=variant_index_list,
            variant_type_list=variant_type_list,
        )

        # ----------------
        # MAIN LOOP
        # ----------------
        for time_step in tqdm(range(config["simulator"]["num_frames"]), leave=False):
            agents.update(time_step=time_step)
            action = agents.get_action_list(obs)
            if np.isnan(action).any() or np.isinf(action).any():
                raise ValueError(f"Action contains infinity or nan: \n{action}")

            # Take the action in the environment and observe the result
            next_obs, reward, terminated, truncated, info = env.step(action)

            # Record the observation
            df = add_obs_to_df(
                df,
                next_obs,
                time_step=(time_step + 1),
                variant_index_list=variant_index_list,
                variant_type_list=variant_type_list,
            )

            # Observe the next state
            obs = next_obs

            # if the environment indicates that the simulation should be terminated, break out of the time step loop
            if terminated or truncated:
                break  # I hate breaks, why does Python make me do it?

        env.close()

        if save_results:
            # write out the package list to help with reproducibility. This seems to be especially important
            # for random number generators, which change based on package level.
            write_package_list(run_folder)

            #
            # Dump data to output file
            #
            table = pa.Table.from_pandas(df)
            logger.debug(f"table \n {table}")

            file_path = expand_path(
                f"episode-{episode}-completed-{datetime.now().strftime('%Y%m%d-%H%M%S')}.parquet",
                # f"episode-{episode}.parquet",
                run_folder,
            )
            logger.info(f"episode {episode} writing output to {file_path}")
            pq.write_table(table, file_path)

        # plot trajectories if specified
        if config["simulator"]["show_trajectories"]:
            plot_trajectories(df, env)

        # move the video to prevent overwriting in the next episode
        if config["visuals"]["store_video"]:
            # change the name of the video file to include the episode
            episode_video_file_path = expand_path(
                f"episode-{episode}-video.{config['visuals']['video_file_extension']}",
                run_folder,
            )
            logger.debug(f"episode video path {episode_video_file_path}")
            shutil.move(video_file_path, episode_video_file_path)

    logger.info("all episodes complete")
    logger.info(f"output written to {run_folder}")


def run_simulator_main(config_file: Path, save_results: bool = True) -> Path:
    """
    Args:
        config_file (Path): path to simulation configuration yaml file
        save_results (bool, optional): whether to save the results or not
    Returns:
        path to the output folder for this simulation run. The output folder will be created if
        it doesn't already exist.
    """
    config = yaml.safe_load(open(config_file))

    # -- 080225 9:15AM
    # Create the output folder
    new_folder_name = f"{config['simulator']['run_main_folder']}/{config['simulator']['run_sub_folder_prefix']}-started-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    new_run_folder = expand_path(new_folder_name, get_project_root())
    new_run_folder.mkdir(parents=True, exist_ok=True)

    # copy the config file to the output folder to keep track of how the data was generated.
    copied_config_file_path = expand_path("config.yaml", new_run_folder)
    shutil.copy(config_file, copied_config_file_path)

    env = create_environment(config=config, run_folder=new_run_folder)
    agents = BoidAgents(simulator_config=config, agent_config=None, env=env)
    run_simulator(
        config=config,
        env=env,
        agents=agents,
        run_folder=new_run_folder,
        save_results=save_results,
    )

    logger.info(
        f"run simulator completed at {datetime.now().strftime('%Y%m%d-%H%M%S')}"
    )

    return new_run_folder


if __name__ == "__main__":
    #
    # Get the config file name if specified on the command line
    #
    parser = argparse.ArgumentParser(
        prog="run_simulator",
        description="Simulates agents in a 3D environment",
        epilog="---",
    )
    parser.add_argument(
        "-cf",
        "--config_file",
        default="collab_env/sim/boids/config.yaml",
        help="path to simulation configuration yaml file",
    )
    parser.add_argument(
        "-s",
        "--save_results",
        action="store_true",
        help="whether to save the results of the simulator.",
    )

    args = parser.parse_args()

    config_filename = expand_path(args.config_file, get_project_root())

    run_simulator_main(config_filename, args.save_results)
