import glob
import os
import subprocess
import sys

import yaml
from tqdm import tqdm

from collab_env.sim.boids.run_simulator import run_simulator_main


def test_gnn3D_with_position_labels():
    #
    # Run simulator
    #
    # subprocess.run([sys.executable, "collab_env/sim/boids/run_simulator.py", "-cf",  "tests/gnn3D_position_labels_config.yaml"])
    sim_run_folder = run_simulator_main(
        config_filename="tests/gnn3D_position_labels_config.yaml"
    )
    assert os.path.exists(sim_run_folder), (
        f"sim_run_folder {sim_run_folder} was returned by run_simulator_main but does not exist"
    )

    output_directory = "tests/gnn3D_pytest_position_labels"
    if os.path.exists(output_directory):
        os.rmdir(output_directory)

    #
    # Build dataset
    #
    result = subprocess.run(
        [
            sys.executable,
            "collab_env/gnn/gnn_3D/build_dataset.py",
            "-d",
            output_directory,
            "-id",
            sim_run_folder,
        ]
    )
    assert result.returncode == 0, (
        f"build_dataset.py was not successful, return code {result.returncode}"
    )

    #
    # Train
    #
    result = subprocess.run(
        [sys.executable, "collab_env/gnn/gnn_3D/train_3DGNN.py", "-d", output_directory]
    )
    assert result.returncode == 0, (
        f"train_3DGNN.py was not successful, return code {result.returncode}"
    )

    #
    # Analyze results
    #

    # Build the agent config file based on the results of the simulator and the trainer
    agent_config = dict()
    agent_config["start_time"] = 0
    agent_config["dataset_metadata_file"] = output_directory + "/processed/gnn3D_data"
    agent_config["model_file"] = (
        output_directory
        + "/training_results/saved_models/gnn-Attention-Linear_epoch_0.pt"
    )

    # To run the rollouts, we need a position file to specify the starting position. This should be a parquet file with
    # columns that include time, type, x, y, z. The type should be "agent". We can use the episode file from the first
    # episode generated by the simulator. We will run analyze_results for each episode the simulator generated above.
    link_to_raw = output_directory + "/raw/link_to_raw_data"
    episode_list = glob.glob(link_to_raw + "/*episode*.parquet")
    for episode_number, episode in enumerate(tqdm(episode_list)):
        agent_config["position_file"] = episode

        # write the agent config file to the output directory and pass the file name to the analyze_results program.
        yaml.dump(agent_config, open(output_directory + "/gnn_agent_config.yaml", "w"))

        result = subprocess.run(
            [
                sys.executable,
                "collab_env/gnn/gnn_3D/analyze_results.py",
                "-d",
                output_directory,
                "-r",
                "-v",
                "-rsd",
                "rollout",
                "-scf",
                "raw/link_to_raw_data/config.yaml",
                "-acf",
                "gnn_agent_config.yaml",
            ]
        )
        assert result.returncode == 0, (
            f"analyze_results.py was not successful for episode file {episode}, return code {result.returncode}"
        )

    #
    # Show trajectories for each validation prediction file
    #
    training_result_directory = output_directory + "/training_results"
    validation_file_list = glob.glob(
        training_result_directory + "/validation_prediction*.parquet"
    )
    for episode_number, episode_file in enumerate(tqdm(validation_file_list)):
        result = subprocess.run(
            [
                sys.executable,
                "collab_env/sim/boids/show_trajectories_all.py",
                "-v",
                "-sp",
                "1500",
                "-td",
                training_result_directory,
                "-tf",
                episode_file.split("/")[-1],
                "-cf",
                output_directory + "/raw/link_to_raw_data/config.yaml",
            ]
        )
        assert result.returncode == 0, (
            f"show_trajectories_all.py was not successful for episode file {episode}, return code {result.returncode}"
        )


if __name__ == "__main__":
    test_gnn3D_with_position_labels()
