{
 "title": "dima test",
 "time": { "from": "2025-11-06T02:43:12.860Z", "to": "2025-11-06T02:44:52.860Z" },
 "templating": {
  "list": [
   {
    "name": "session_id",
    "query": "SELECT \n  s.session_id as __value,\n  s.session_name as __text\nFROM sessions s\nORDER BY s.created_at DESC"
   },
   {
    "name": "episode_id",
    "label": "Episode",
    "query": "SELECT \n  e.episode_id as __value,\n  'Episode ' || e.episode_number || ' (' || e.num_frames || ' frames, ' || e.num_agents || ' agents)' as __text\nFROM episodes e\nWHERE e.session_id = '$session_id'\nORDER BY e.episode_number"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Sessions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tracking_analytics",
     "rawSql": "select count(*) as __value, count(*) || 'sessions' as __text from sessions"
    }
   ]
  },
  {
   "title": "Total Episodes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "tracking_analytics", "rawSql": "select count(*) from episodes" }
   ]
  },
  {
   "title": "Total agents",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tracking_analytics",
     "rawSql": "select count(distinct(o.agent_id)) from observations o where o.episode_id = '$episode_id'"
    }
   ]
  },
  {
   "title": "Speeds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "tracking_analytics",
     "rawSql": "select e.created_at + (o.time_index / e.frame_rate) * interval '1 second' as \"time\", sqrt(o.v_x*o.v_x + o.v_y * o.v_y + o.v_z * o.v_z) as \"speed\", agent_id::text as \"metric\"\nfrom observations o, episodes e\nwhere e.episode_id = o.episode_id and o.episode_id = '$episode_id' and agent_type_id='agent'\nORDER BY time asc"
    }
   ]
  },
  {
   "title": "Speed distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "tracking_analytics",
     "rawSql": "SELECT\n    sqrt(v_x*v_x + v_y*v_y + COALESCE(v_z*v_z, 0))  as speed\nFROM observations\nWHERE episode_id = '$episode_id'\n  AND agent_type_id = 'agent'\n  AND v_x IS NOT NULL\n"
    }
   ]
  }
 ]
}